# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.helpers:
        class: AppBundle\Helpers
        
    app.form.user_edit:
        class: AppBundle\Form\UserEditType
        arguments: ['@security.token_storage']
        tags:
            - { name: form.type }
    
    app.form.event:
        class: AppBundle\Form\EventType
        arguments: ['@service_container']
        tags:
            - { name: form.type }
            
    app.sitemap:
        class: AppBundle\SiteMap
        arguments: ['@router', '@doctrine.orm.entity_manager']
            
# Twig extensions
    app.twig_extension:
        class: AppBundle\Twig\AppExtension
        public: false
        arguments: [ '@responsive_image.style_manager', '@app.helpers' ]
        tags:
            - { name: twig.extension }